### ISSUE TITLE
Additional tags support

### ISSUE THREAD

**Issue by michelepeghini** [aswinkumar863/smarty-vscode-support#7]
Hi,
I need to add support for `<{` and `}>` tags. Do you think it would be hard to accomplish?
I see that the parsing rules are defined in `smarty.tmLanguage.json` file. Is that the only file that needs modification in order to add the tag support or are there other files that needs changing?
This is not a feature request, necessarily, I'm happy to simply fork the repo, but any help would be hugely appreciated. Thank you.

**Comment by aswinkumar863** [comment]
> Hi,
> I need to add support for `<{` and `}>` tags. Do you think it would be hard to accomplish?
> I see that the parsing rules are defined in `smarty.tmLanguage.json` file. Is that the only file that needs modification in order to add the tag support or are there other files that needs changing?
> This is not a feature request, necessarily, I'm happy to simply fork the repo, but any help would be hugely appreciated. Thank you.

I don't think syntax highlighting is hard to accomplish as you said. But code formatting may not be accurate because of the formatter is HTML based. This delimiter has a high chance of getting conflicted in HTML formatting because of `<` and `>`.

I recommend you to fork the repo and get started. Congrats.

**Comment by michelepeghini** [comment]
Cool. Thanks for the swift reply. 😃
